default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost
  user: postgres
  password: root

development:
  <<: *default
  database: associasion_development

test:
  <<: *default
  database: associasion_test

production:
  <<: *default
  database: associasion_production
  username: associasion
  password: <%= ENV['ASSOCIASION_DATABASE_PASSWORD'] %>
